// Generated by CIRCT firtool-1.61.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module ScratchpadSlavePort(
  input         clock,
                reset,
  output        auto_in_a_ready,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input         auto_in_a_valid,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [2:0]  auto_in_a_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                auto_in_a_bits_param,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [1:0]  auto_in_a_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [10:0] auto_in_a_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [31:0] auto_in_a_bits_address,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [3:0]  auto_in_a_bits_mask,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input  [31:0] auto_in_a_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input         auto_in_a_bits_corrupt,	// src/main/scala/diplomacy/LazyModule.scala:374:18
                auto_in_d_ready,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output        auto_in_d_valid,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [2:0]  auto_in_d_bits_opcode,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [1:0]  auto_in_d_bits_size,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [10:0] auto_in_d_bits_source,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  output [31:0] auto_in_d_bits_data,	// src/main/scala/diplomacy/LazyModule.scala:374:18
  input         io_dmem_req_ready,	// src/main/scala/rocket/ScratchpadSlavePort.scala:37:16
  output        io_dmem_req_valid,	// src/main/scala/rocket/ScratchpadSlavePort.scala:37:16
  output [31:0] io_dmem_req_bits_addr,	// src/main/scala/rocket/ScratchpadSlavePort.scala:37:16
  output [4:0]  io_dmem_req_bits_cmd,	// src/main/scala/rocket/ScratchpadSlavePort.scala:37:16
  output [1:0]  io_dmem_req_bits_size,	// src/main/scala/rocket/ScratchpadSlavePort.scala:37:16
  output        io_dmem_s1_kill,	// src/main/scala/rocket/ScratchpadSlavePort.scala:37:16
  output [31:0] io_dmem_s1_data_data,	// src/main/scala/rocket/ScratchpadSlavePort.scala:37:16
  output [3:0]  io_dmem_s1_data_mask,	// src/main/scala/rocket/ScratchpadSlavePort.scala:37:16
  input         io_dmem_s2_nack,	// src/main/scala/rocket/ScratchpadSlavePort.scala:37:16
                io_dmem_resp_valid,	// src/main/scala/rocket/ScratchpadSlavePort.scala:37:16
  input  [31:0] io_dmem_resp_bits_data_raw	// src/main/scala/rocket/ScratchpadSlavePort.scala:37:16
);

  wire        nodeIn_a_valid = auto_in_a_valid;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [2:0]  nodeIn_a_bits_opcode = auto_in_a_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [2:0]  nodeIn_a_bits_param = auto_in_a_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [1:0]  nodeIn_a_bits_size = auto_in_a_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [10:0] nodeIn_a_bits_source = auto_in_a_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [31:0] nodeIn_a_bits_address = auto_in_a_bits_address;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [3:0]  nodeIn_a_bits_mask = auto_in_a_bits_mask;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [31:0] nodeIn_a_bits_data = auto_in_a_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        nodeIn_a_bits_corrupt = auto_in_a_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire        nodeIn_d_ready = auto_in_d_ready;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [1:0]  nodeIn_d_bits_param = 2'h0;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  wire [1:0]  io_dmem_req_bits_req_dprv = 2'h0;	// src/main/scala/rocket/ScratchpadSlavePort.scala:59:21
  wire [1:0]  nodeIn_d_bits_d_param = 2'h0;	// src/main/scala/tilelink/Edges.scala:771:17
  wire [1:0]  nodeIn_d_bits_d_1_param = 2'h0;	// src/main/scala/tilelink/Edges.scala:787:17
  wire [2:0]  nodeIn_d_bits_d_1_opcode = 3'h1;	// src/main/scala/tilelink/Edges.scala:787:17
  wire [2:0]  nodeIn_d_bits_d_opcode = 3'h0;	// src/main/scala/tilelink/Edges.scala:771:17
  wire        io_dmem_req_bits_req_phys = 1'h1;	// src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rocket/ScratchpadSlavePort.scala:59:21
  wire        io_dmem_req_bits_req_no_xcpt = 1'h1;	// src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rocket/ScratchpadSlavePort.scala:59:21
  wire [6:0]  io_dmem_req_bits_req_tag = 7'h0;	// src/main/scala/rocket/ScratchpadSlavePort.scala:59:21, :89:15
  wire [3:0]  io_dmem_req_bits_req_mask = 4'h0;	// src/main/scala/rocket/ScratchpadSlavePort.scala:59:21, src/main/scala/tilelink/Bundles.scala:259:74
  wire [31:0] io_dmem_req_bits_req_data = 32'h0;	// src/main/scala/rocket/ScratchpadSlavePort.scala:59:21, src/main/scala/tilelink/Bundles.scala:259:74
  wire [31:0] nodeIn_d_bits_d_data = 32'h0;	// src/main/scala/tilelink/Bundles.scala:259:74, src/main/scala/tilelink/Edges.scala:771:17
  wire [31:0] nodeIn_d_bits_d_1_data = 32'h0;	// src/main/scala/tilelink/Bundles.scala:259:74, src/main/scala/tilelink/Edges.scala:787:17
  wire        nodeIn_d_bits_sink = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:37:16, :59:21, :118:24, src/main/scala/tilelink/Edges.scala:771:17, :787:17
  wire        nodeIn_d_bits_denied = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:37:16, :59:21, :118:24, src/main/scala/tilelink/Edges.scala:771:17, :787:17
  wire        nodeIn_d_bits_corrupt = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:37:16, :59:21, :118:24, src/main/scala/tilelink/Edges.scala:771:17, :787:17
  wire        io_dmem_req_bits_req_signed = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:37:16, :59:21, :118:24, src/main/scala/tilelink/Edges.scala:771:17, :787:17
  wire        io_dmem_req_bits_req_dv = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:37:16, :59:21, :118:24, src/main/scala/tilelink/Edges.scala:771:17, :787:17
  wire        io_dmem_req_bits_req_no_alloc = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:37:16, :59:21, :118:24, src/main/scala/tilelink/Edges.scala:771:17, :787:17
  wire        nodeIn_d_bits_d_sink = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:37:16, :59:21, :118:24, src/main/scala/tilelink/Edges.scala:771:17, :787:17
  wire        nodeIn_d_bits_d_denied = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:37:16, :59:21, :118:24, src/main/scala/tilelink/Edges.scala:771:17, :787:17
  wire        nodeIn_d_bits_d_corrupt = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:37:16, :59:21, :118:24, src/main/scala/tilelink/Edges.scala:771:17, :787:17
  wire        nodeIn_d_bits_d_1_sink = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:37:16, :59:21, :118:24, src/main/scala/tilelink/Edges.scala:771:17, :787:17
  wire        nodeIn_d_bits_d_1_denied = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:37:16, :59:21, :118:24, src/main/scala/tilelink/Edges.scala:771:17, :787:17
  wire        nodeIn_d_bits_d_1_corrupt = 1'h0;	// src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:37:16, :59:21, :118:24, src/main/scala/tilelink/Edges.scala:771:17, :787:17
  reg  [2:0]  state;	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24
  wire        _io_dmem_req_bits_T_2 = state == 3'h4;	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24, :49:17
  reg  [2:0]  acq_opcode;	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
  reg  [2:0]  acq_param;	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
  reg  [1:0]  acq_size;	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
  wire [1:0]  nodeIn_d_bits_d_size = acq_size;	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18, src/main/scala/tilelink/Edges.scala:771:17
  wire [1:0]  nodeIn_d_bits_d_1_size = acq_size;	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18, src/main/scala/tilelink/Edges.scala:787:17
  reg  [10:0] acq_source;	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
  wire [10:0] nodeIn_d_bits_d_source = acq_source;	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18, src/main/scala/tilelink/Edges.scala:771:17
  wire [10:0] nodeIn_d_bits_d_1_source = acq_source;	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18, src/main/scala/tilelink/Edges.scala:787:17
  reg  [31:0] acq_address;	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
  reg  [3:0]  acq_mask;	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
  reg  [31:0] acq_data;	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
  reg         acq_corrupt;	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
  wire        _ready_T = state == 3'h0;	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24, src/main/scala/util/package.scala:16:47
  wire        _nodeIn_d_bits_data_T = state == 3'h2;	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24, :48:38, src/main/scala/util/package.scala:16:47
  wire        ready_likely = _ready_T | _nodeIn_d_bits_data_T;	// src/main/scala/util/package.scala:16:47, :81:59
  wire        ready =
    _ready_T | _nodeIn_d_bits_data_T & io_dmem_resp_valid & nodeIn_d_ready;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:104:{35,78}, src/main/scala/util/package.scala:16:47
  wire        _io_dmem_req_bits_T = state == 3'h3;	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24, :52:36, :105:57
  wire        dmem_req_valid = nodeIn_a_valid & ready | _io_dmem_req_bits_T;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:47:30, :104:35, :105:{38,48,57}
  wire        dmem_req_valid_likely = nodeIn_a_valid & ready_likely | _io_dmem_req_bits_T;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:105:57, :106:{48,65}, src/main/scala/util/package.scala:81:59
  wire        nodeIn_a_ready = io_dmem_req_ready & ready;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:104:35, :110:40
  wire [2:0]  _io_dmem_req_bits_T_1_opcode =
    _io_dmem_req_bits_T ? acq_opcode : nodeIn_a_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:55:18, :105:57, :111:41
  wire [2:0]  _io_dmem_req_bits_T_1_param =
    _io_dmem_req_bits_T ? acq_param : nodeIn_a_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:55:18, :105:57, :111:41
  wire [1:0]  _io_dmem_req_bits_T_1_size =
    _io_dmem_req_bits_T ? acq_size : nodeIn_a_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:55:18, :105:57, :111:41
  wire [1:0]  io_dmem_req_bits_req_size;	// src/main/scala/rocket/ScratchpadSlavePort.scala:59:21
  assign io_dmem_req_bits_req_size = _io_dmem_req_bits_T_1_size;	// src/main/scala/rocket/ScratchpadSlavePort.scala:59:21, :111:41
  wire [1:0]  io_dmem_req_bits_mask_full_desired_mask_size;	// src/main/scala/rocket/AMOALU.scala:11:18
  assign io_dmem_req_bits_mask_full_desired_mask_size = _io_dmem_req_bits_T_1_size;	// src/main/scala/rocket/AMOALU.scala:11:18, src/main/scala/rocket/ScratchpadSlavePort.scala:111:41
  wire [31:0] io_dmem_req_bits_req_addr =
    _io_dmem_req_bits_T ? acq_address : nodeIn_a_bits_address;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:55:18, :59:21, :105:57, :111:41
  reg  [3:0]  casez_tmp;	// src/main/scala/chisel3/util/Mux.scala:77:13
  always @(*) begin	// src/main/scala/chisel3/util/Mux.scala:77:13
    casez (_io_dmem_req_bits_T_1_param)	// src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rocket/ScratchpadSlavePort.scala:111:41
      3'b000:
        casez_tmp = 4'hC;	// src/main/scala/chisel3/util/Mux.scala:77:13
      3'b001:
        casez_tmp = 4'hD;	// src/main/scala/chisel3/util/Mux.scala:77:13
      3'b010:
        casez_tmp = 4'hE;	// src/main/scala/chisel3/util/Mux.scala:77:13
      3'b011:
        casez_tmp = 4'hF;	// src/main/scala/chisel3/util/Mux.scala:77:13
      3'b100:
        casez_tmp = 4'h8;	// src/main/scala/chisel3/util/Mux.scala:77:13
      3'b101:
        casez_tmp = 4'h0;	// src/main/scala/chisel3/util/Mux.scala:77:13
      3'b110:
        casez_tmp = 4'h0;	// src/main/scala/chisel3/util/Mux.scala:77:13
      default:
        casez_tmp = 4'h0;	// src/main/scala/chisel3/util/Mux.scala:77:13
    endcase	// src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rocket/ScratchpadSlavePort.scala:111:41
  end // always @(*)
  wire        io_dmem_req_bits_mask_full_desired_mask_upper =
    io_dmem_req_bits_req_addr[0] | (|io_dmem_req_bits_mask_full_desired_mask_size);	// src/main/scala/rocket/AMOALU.scala:11:18, :19:{27,42,53}, src/main/scala/rocket/ScratchpadSlavePort.scala:59:21
  wire        io_dmem_req_bits_mask_full_desired_mask_lower =
    ~(io_dmem_req_bits_req_addr[0]);	// src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/rocket/AMOALU.scala:19:27, :20:22, src/main/scala/rocket/ScratchpadSlavePort.scala:55:18, :59:21
  wire [1:0]  _io_dmem_req_bits_mask_full_desired_mask_T =
    {io_dmem_req_bits_mask_full_desired_mask_upper,
     io_dmem_req_bits_mask_full_desired_mask_lower};	// src/main/scala/rocket/AMOALU.scala:19:42, :20:22, :21:16
  wire [1:0]  io_dmem_req_bits_mask_full_desired_mask_upper_1 =
    (io_dmem_req_bits_req_addr[1] ? _io_dmem_req_bits_mask_full_desired_mask_T : 2'h0)
    | {2{io_dmem_req_bits_mask_full_desired_mask_size[1]}};	// src/main/scala/rocket/AMOALU.scala:11:18, :19:{22,27,42,47,53}, :21:16, src/main/scala/rocket/ScratchpadSlavePort.scala:59:21
  wire [1:0]  io_dmem_req_bits_mask_full_desired_mask_lower_1 =
    io_dmem_req_bits_req_addr[1] ? 2'h0 : _io_dmem_req_bits_mask_full_desired_mask_T;	// src/main/scala/rocket/AMOALU.scala:19:27, :20:22, :21:16, src/main/scala/rocket/ScratchpadSlavePort.scala:59:21
  wire [3:0]  io_dmem_req_bits_mask_full_desired_mask =
    {io_dmem_req_bits_mask_full_desired_mask_upper_1,
     io_dmem_req_bits_mask_full_desired_mask_lower_1};	// src/main/scala/rocket/AMOALU.scala:19:42, :20:22, :21:16
  wire        io_dmem_req_bits_mask_full =
    &((_io_dmem_req_bits_T ? acq_mask : nodeIn_a_bits_mask)
      | ~io_dmem_req_bits_mask_full_desired_mask);	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/AMOALU.scala:21:16, src/main/scala/rocket/ScratchpadSlavePort.scala:55:18, :80:{17,19,34}, :105:57, :111:41
  wire [4:0]  io_dmem_req_bits_req_cmd =
    _io_dmem_req_bits_T_2 | _io_dmem_req_bits_T_1_opcode == 3'h1
    & io_dmem_req_bits_mask_full
      ? 5'h1
      : _io_dmem_req_bits_T_1_opcode == 3'h4
          ? 5'h0
          : _io_dmem_req_bits_T_1_opcode == 3'h3
              ? {1'h0,
                 _io_dmem_req_bits_T_1_param == 3'h3
                   ? 4'h4
                   : _io_dmem_req_bits_T_1_param == 3'h2
                       ? 4'hB
                       : _io_dmem_req_bits_T_1_param == 3'h1
                           ? 4'hA
                           : _io_dmem_req_bits_T_1_param == 3'h0 ? 4'h9 : 4'h0}
              : _io_dmem_req_bits_T_1_opcode == 3'h2
                  ? {1'h0, casez_tmp}
                  : _io_dmem_req_bits_T_1_opcode == 3'h1
                      ? 5'h11
                      : {4'h0, _io_dmem_req_bits_T_1_opcode == 3'h0};	// src/main/scala/chisel3/util/Mux.scala:77:13, src/main/scala/diplomacy/LazyModule.scala:374:18, src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:37:16, :48:38, :49:17, :52:36, :59:21, :60:15, :80:34, :82:{30,43,73,88}, :83:17, :111:41, :118:24, src/main/scala/tilelink/Bundles.scala:259:74, src/main/scala/tilelink/Edges.scala:771:17, :787:17
  wire        nodeIn_d_valid = io_dmem_resp_valid | state == 3'h5;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:46:24, :50:39, :117:{41,50}
  wire        _nodeIn_d_bits_T_2 = acq_opcode == 3'h0 | acq_opcode == 3'h1;	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18, src/main/scala/util/package.scala:16:47, :81:59
  wire [2:0]  nodeIn_d_bits_opcode = {2'h0, ~_nodeIn_d_bits_T_2};	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:118:24, src/main/scala/util/package.scala:81:59
  wire [1:0]  nodeIn_d_bits_size =
    _nodeIn_d_bits_T_2 ? nodeIn_d_bits_d_size : nodeIn_d_bits_d_1_size;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:118:24, src/main/scala/tilelink/Edges.scala:771:17, :787:17, src/main/scala/util/package.scala:81:59
  wire [10:0] nodeIn_d_bits_source =
    _nodeIn_d_bits_T_2 ? nodeIn_d_bits_d_source : nodeIn_d_bits_d_1_source;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:118:24, src/main/scala/tilelink/Edges.scala:771:17, :787:17, src/main/scala/util/package.scala:81:59
  reg  [31:0] nodeIn_d_bits_data_r;	// src/main/scala/util/package.scala:88:63
  wire [31:0] nodeIn_d_bits_data =
    _nodeIn_d_bits_data_T ? io_dmem_resp_bits_data_raw : nodeIn_d_bits_data_r;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/util/package.scala:16:47, :88:{42,63}
  always @(posedge clock) begin
    if (reset)
      state <= 3'h4;	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24
    else if (dmem_req_valid & io_dmem_req_ready)	// src/main/scala/rocket/ScratchpadSlavePort.scala:47:30, :53:26
      state <= 3'h1;	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24
    else if (io_dmem_s2_nack)	// src/main/scala/rocket/ScratchpadSlavePort.scala:37:16
      state <= 3'h3;	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24, :52:36
    else if (nodeIn_d_ready & nodeIn_d_valid)	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/diplomacy/Nodes.scala:1214:17
      state <= 3'h0;	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24
    else if (io_dmem_resp_valid)	// src/main/scala/rocket/ScratchpadSlavePort.scala:37:16
      state <= 3'h5;	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24, :50:39
    else if (_io_dmem_req_bits_T_2 & nodeIn_a_valid)	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:49:{17,28}
      state <= 3'h0;	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24
    else if (state == 3'h1)	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24, :48:17
      state <= 3'h2;	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24, :48:38
    if (nodeIn_a_ready & nodeIn_a_valid) begin	// src/main/scala/chisel3/util/Decoupled.scala:52:35, src/main/scala/diplomacy/Nodes.scala:1214:17
      acq_opcode <= nodeIn_a_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
      acq_param <= nodeIn_a_bits_param;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
      acq_size <= nodeIn_a_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
      acq_source <= nodeIn_a_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
      acq_address <= nodeIn_a_bits_address;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
      acq_mask <= nodeIn_a_bits_mask;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
      acq_data <= nodeIn_a_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
      acq_corrupt <= nodeIn_a_bits_corrupt;	// src/main/scala/diplomacy/Nodes.scala:1214:17, src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
    end
    if (_nodeIn_d_bits_data_T)	// src/main/scala/util/package.scala:16:47
      nodeIn_d_bits_data_r <= io_dmem_resp_bits_data_raw;	// src/main/scala/util/package.scala:88:63
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;
        end
        state = _RANDOM[2'h0][2:0];	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24
        acq_opcode = _RANDOM[2'h0][5:3];	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24, :55:18
        acq_param = _RANDOM[2'h0][8:6];	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24, :55:18
        acq_size = _RANDOM[2'h0][10:9];	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24, :55:18
        acq_source = _RANDOM[2'h0][21:11];	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24, :55:18
        acq_address = {_RANDOM[2'h0][31:22], _RANDOM[2'h1][21:0]};	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24, :55:18
        acq_mask = _RANDOM[2'h1][25:22];	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
        acq_data = {_RANDOM[2'h1][31:26], _RANDOM[2'h2][25:0]};	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
        acq_corrupt = _RANDOM[2'h2][26];	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
        nodeIn_d_bits_data_r = {_RANDOM[2'h2][31:27], _RANDOM[2'h3][26:0]};	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18, src/main/scala/util/package.scala:88:63
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign auto_in_a_ready = nodeIn_a_ready;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_valid = nodeIn_d_valid;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_bits_opcode = nodeIn_d_bits_opcode;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_bits_size = nodeIn_d_bits_size;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_bits_source = nodeIn_d_bits_source;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign auto_in_d_bits_data = nodeIn_d_bits_data;	// src/main/scala/diplomacy/Nodes.scala:1214:17
  assign io_dmem_req_valid = dmem_req_valid_likely;	// src/main/scala/rocket/ScratchpadSlavePort.scala:106:65
  assign io_dmem_req_bits_addr = io_dmem_req_bits_req_addr;	// src/main/scala/rocket/ScratchpadSlavePort.scala:59:21
  assign io_dmem_req_bits_cmd = io_dmem_req_bits_req_cmd;	// src/main/scala/rocket/ScratchpadSlavePort.scala:59:21
  assign io_dmem_req_bits_size = io_dmem_req_bits_req_size;	// src/main/scala/rocket/ScratchpadSlavePort.scala:59:21
  assign io_dmem_s1_kill = state != 3'h1;	// src/main/scala/rocket/ScratchpadSlavePort.scala:46:24, :114:30
  assign io_dmem_s1_data_data = acq_data;	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
  assign io_dmem_s1_data_mask = acq_mask;	// src/main/scala/rocket/ScratchpadSlavePort.scala:55:18
endmodule

